version: '3.7'
services:
  client:
    build:
      context: ./client
      dockerfile: ../docker/client/Dockerfile.dev
    volumes:
      - ./client:/app
    restart: always
    stdin_open: true
    ports:
      - "3001:3001"